# Reto 6: Manejo de Excepciones en POO

## Excepciones tomadas

- Reto_1_Ejercicio_1_con_excepciones.py: OperacionInvalida, ZeroDivisionError
- Reto_1_Ejercicio_2_con_excepciones.py: StringVacia, InputInvalido
- Reto_1_Ejercicio_3_con_excepciones.py: ListaVaciaError, NumeroInvalidoError
- Reto_1_Ejercicio_4_con_excepciones.py: ListaVaciaError, ElementosInsuficientesError, NumeroInvalidoError
- Reto_1_Ejercicio_5_con_excepciones.py: ListaVaciaError, PalabraInvalidaError, StringVaciaError

- point_module.py: InvalidPointError
- line_module.py: InvalidEdgeError
- shape_module.py: ShapeError, InvalidEdgeError, InsufficientDataError,   GeometricCalculationError
- rectangle_module.py: InvalidDimensionError, InvalidRectangleError
- triangle_module.py: TrianguloInvalidoError